// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/logproxy.proto

package com.oceanbase.clogproxy.common.packet.protocol;

public final class LogProxyProto {
  private LogProxyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PbPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:oms.PbPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * HeaderType
     * </pre>
     *
     * <code>int32 type = 1;</code>
     * @return The type.
     */
    int getType();

    /**
     * <pre>
     *CompressType
     * </pre>
     *
     * <code>int32 compress_type = 2;</code>
     * @return The compressType.
     */
    int getCompressType();

    /**
     * <pre>
     * resevered for other options
     * </pre>
     *
     * <code>bytes payload = 100;</code>
     * @return The payload.
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code oms.PbPacket}
   */
  public static final class PbPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:oms.PbPacket)
      PbPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PbPacket.newBuilder() to construct.
    private PbPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PbPacket() {
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PbPacket();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PbPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              type_ = input.readInt32();
              break;
            }
            case 16: {

              compressType_ = input.readInt32();
              break;
            }
            case 802: {

              payload_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.internal_static_oms_PbPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.internal_static_oms_PbPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket.class, com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     * HeaderType
     * </pre>
     *
     * <code>int32 type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }

    public static final int COMPRESS_TYPE_FIELD_NUMBER = 2;
    private int compressType_;
    /**
     * <pre>
     *CompressType
     * </pre>
     *
     * <code>int32 compress_type = 2;</code>
     * @return The compressType.
     */
    @java.lang.Override
    public int getCompressType() {
      return compressType_;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 100;
    private com.google.protobuf.ByteString payload_;
    /**
     * <pre>
     * resevered for other options
     * </pre>
     *
     * <code>bytes payload = 100;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeInt32(1, type_);
      }
      if (compressType_ != 0) {
        output.writeInt32(2, compressType_);
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(100, payload_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (compressType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, compressType_);
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(100, payload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket)) {
        return super.equals(obj);
      }
      com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket other = (com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket) obj;

      if (getType()
          != other.getType()) return false;
      if (getCompressType()
          != other.getCompressType()) return false;
      if (!getPayload()
          .equals(other.getPayload())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + COMPRESS_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getCompressType();
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code oms.PbPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:oms.PbPacket)
        com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.internal_static_oms_PbPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.internal_static_oms_PbPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket.class, com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket.Builder.class);
      }

      // Construct using com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        compressType_ = 0;

        payload_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.internal_static_oms_PbPacket_descriptor;
      }

      @java.lang.Override
      public com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket getDefaultInstanceForType() {
        return com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket.getDefaultInstance();
      }

      @java.lang.Override
      public com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket build() {
        com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket buildPartial() {
        com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket result = new com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket(this);
        result.type_ = type_;
        result.compressType_ = compressType_;
        result.payload_ = payload_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket) {
          return mergeFrom((com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket other) {
        if (other == com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getCompressType() != 0) {
          setCompressType(other.getCompressType());
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       * HeaderType
       * </pre>
       *
       * <code>int32 type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       * HeaderType
       * </pre>
       *
       * <code>int32 type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * HeaderType
       * </pre>
       *
       * <code>int32 type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int compressType_ ;
      /**
       * <pre>
       *CompressType
       * </pre>
       *
       * <code>int32 compress_type = 2;</code>
       * @return The compressType.
       */
      @java.lang.Override
      public int getCompressType() {
        return compressType_;
      }
      /**
       * <pre>
       *CompressType
       * </pre>
       *
       * <code>int32 compress_type = 2;</code>
       * @param value The compressType to set.
       * @return This builder for chaining.
       */
      public Builder setCompressType(int value) {
        
        compressType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *CompressType
       * </pre>
       *
       * <code>int32 compress_type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCompressType() {
        
        compressType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * resevered for other options
       * </pre>
       *
       * <code>bytes payload = 100;</code>
       * @return The payload.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <pre>
       * resevered for other options
       * </pre>
       *
       * <code>bytes payload = 100;</code>
       * @param value The payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * resevered for other options
       * </pre>
       *
       * <code>bytes payload = 100;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:oms.PbPacket)
    }

    // @@protoc_insertion_point(class_scope:oms.PbPacket)
    private static final com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket();
    }

    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PbPacket>
        PARSER = new com.google.protobuf.AbstractParser<PbPacket>() {
      @java.lang.Override
      public PbPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PbPacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PbPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PbPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.PbPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ClientHandShakeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:oms.ClientHandShake)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * LogType
     * </pre>
     *
     * <code>int32 log_type = 1;</code>
     * @return The logType.
     */
    int getLogType();

    /**
     * <code>string client_ip = 2;</code>
     * @return The clientIp.
     */
    java.lang.String getClientIp();
    /**
     * <code>string client_ip = 2;</code>
     * @return The bytes for clientIp.
     */
    com.google.protobuf.ByteString
        getClientIpBytes();

    /**
     * <code>string client_id = 3;</code>
     * @return The clientId.
     */
    java.lang.String getClientId();
    /**
     * <code>string client_id = 3;</code>
     * @return The bytes for clientId.
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    /**
     * <code>string client_version = 4;</code>
     * @return The clientVersion.
     */
    java.lang.String getClientVersion();
    /**
     * <code>string client_version = 4;</code>
     * @return The bytes for clientVersion.
     */
    com.google.protobuf.ByteString
        getClientVersionBytes();

    /**
     * <code>bool enable_monitor = 5;</code>
     * @return The enableMonitor.
     */
    boolean getEnableMonitor();

    /**
     * <code>string configuration = 6;</code>
     * @return The configuration.
     */
    java.lang.String getConfiguration();
    /**
     * <code>string configuration = 6;</code>
     * @return The bytes for configuration.
     */
    com.google.protobuf.ByteString
        getConfigurationBytes();
  }
  /**
   * Protobuf type {@code oms.ClientHandShake}
   */
  public static final class ClientHandShake extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:oms.ClientHandShake)
      ClientHandShakeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClientHandShake.newBuilder() to construct.
    private ClientHandShake(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientHandShake() {
      clientIp_ = "";
      clientId_ = "";
      clientVersion_ = "";
      configuration_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ClientHandShake();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClientHandShake(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              logType_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              clientIp_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              clientId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              clientVersion_ = s;
              break;
            }
            case 40: {

              enableMonitor_ = input.readBool();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              configuration_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.internal_static_oms_ClientHandShake_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.internal_static_oms_ClientHandShake_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake.class, com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake.Builder.class);
    }

    public static final int LOG_TYPE_FIELD_NUMBER = 1;
    private int logType_;
    /**
     * <pre>
     * LogType
     * </pre>
     *
     * <code>int32 log_type = 1;</code>
     * @return The logType.
     */
    @java.lang.Override
    public int getLogType() {
      return logType_;
    }

    public static final int CLIENT_IP_FIELD_NUMBER = 2;
    private volatile java.lang.Object clientIp_;
    /**
     * <code>string client_ip = 2;</code>
     * @return The clientIp.
     */
    @java.lang.Override
    public java.lang.String getClientIp() {
      java.lang.Object ref = clientIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientIp_ = s;
        return s;
      }
    }
    /**
     * <code>string client_ip = 2;</code>
     * @return The bytes for clientIp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientIpBytes() {
      java.lang.Object ref = clientIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENT_ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object clientId_;
    /**
     * <code>string client_id = 3;</code>
     * @return The clientId.
     */
    @java.lang.Override
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      }
    }
    /**
     * <code>string client_id = 3;</code>
     * @return The bytes for clientId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENT_VERSION_FIELD_NUMBER = 4;
    private volatile java.lang.Object clientVersion_;
    /**
     * <code>string client_version = 4;</code>
     * @return The clientVersion.
     */
    @java.lang.Override
    public java.lang.String getClientVersion() {
      java.lang.Object ref = clientVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string client_version = 4;</code>
     * @return The bytes for clientVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientVersionBytes() {
      java.lang.Object ref = clientVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENABLE_MONITOR_FIELD_NUMBER = 5;
    private boolean enableMonitor_;
    /**
     * <code>bool enable_monitor = 5;</code>
     * @return The enableMonitor.
     */
    @java.lang.Override
    public boolean getEnableMonitor() {
      return enableMonitor_;
    }

    public static final int CONFIGURATION_FIELD_NUMBER = 6;
    private volatile java.lang.Object configuration_;
    /**
     * <code>string configuration = 6;</code>
     * @return The configuration.
     */
    @java.lang.Override
    public java.lang.String getConfiguration() {
      java.lang.Object ref = configuration_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        configuration_ = s;
        return s;
      }
    }
    /**
     * <code>string configuration = 6;</code>
     * @return The bytes for configuration.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConfigurationBytes() {
      java.lang.Object ref = configuration_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        configuration_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (logType_ != 0) {
        output.writeInt32(1, logType_);
      }
      if (!getClientIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clientIp_);
      }
      if (!getClientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, clientId_);
      }
      if (!getClientVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, clientVersion_);
      }
      if (enableMonitor_ != false) {
        output.writeBool(5, enableMonitor_);
      }
      if (!getConfigurationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, configuration_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (logType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, logType_);
      }
      if (!getClientIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clientIp_);
      }
      if (!getClientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, clientId_);
      }
      if (!getClientVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, clientVersion_);
      }
      if (enableMonitor_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, enableMonitor_);
      }
      if (!getConfigurationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, configuration_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake)) {
        return super.equals(obj);
      }
      com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake other = (com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake) obj;

      if (getLogType()
          != other.getLogType()) return false;
      if (!getClientIp()
          .equals(other.getClientIp())) return false;
      if (!getClientId()
          .equals(other.getClientId())) return false;
      if (!getClientVersion()
          .equals(other.getClientVersion())) return false;
      if (getEnableMonitor()
          != other.getEnableMonitor()) return false;
      if (!getConfiguration()
          .equals(other.getConfiguration())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOG_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getLogType();
      hash = (37 * hash) + CLIENT_IP_FIELD_NUMBER;
      hash = (53 * hash) + getClientIp().hashCode();
      hash = (37 * hash) + CLIENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId().hashCode();
      hash = (37 * hash) + CLIENT_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getClientVersion().hashCode();
      hash = (37 * hash) + ENABLE_MONITOR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getEnableMonitor());
      hash = (37 * hash) + CONFIGURATION_FIELD_NUMBER;
      hash = (53 * hash) + getConfiguration().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code oms.ClientHandShake}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:oms.ClientHandShake)
        com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShakeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.internal_static_oms_ClientHandShake_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.internal_static_oms_ClientHandShake_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake.class, com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake.Builder.class);
      }

      // Construct using com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        logType_ = 0;

        clientIp_ = "";

        clientId_ = "";

        clientVersion_ = "";

        enableMonitor_ = false;

        configuration_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.internal_static_oms_ClientHandShake_descriptor;
      }

      @java.lang.Override
      public com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake getDefaultInstanceForType() {
        return com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake.getDefaultInstance();
      }

      @java.lang.Override
      public com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake build() {
        com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake buildPartial() {
        com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake result = new com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake(this);
        result.logType_ = logType_;
        result.clientIp_ = clientIp_;
        result.clientId_ = clientId_;
        result.clientVersion_ = clientVersion_;
        result.enableMonitor_ = enableMonitor_;
        result.configuration_ = configuration_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake) {
          return mergeFrom((com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake other) {
        if (other == com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake.getDefaultInstance()) return this;
        if (other.getLogType() != 0) {
          setLogType(other.getLogType());
        }
        if (!other.getClientIp().isEmpty()) {
          clientIp_ = other.clientIp_;
          onChanged();
        }
        if (!other.getClientId().isEmpty()) {
          clientId_ = other.clientId_;
          onChanged();
        }
        if (!other.getClientVersion().isEmpty()) {
          clientVersion_ = other.clientVersion_;
          onChanged();
        }
        if (other.getEnableMonitor() != false) {
          setEnableMonitor(other.getEnableMonitor());
        }
        if (!other.getConfiguration().isEmpty()) {
          configuration_ = other.configuration_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int logType_ ;
      /**
       * <pre>
       * LogType
       * </pre>
       *
       * <code>int32 log_type = 1;</code>
       * @return The logType.
       */
      @java.lang.Override
      public int getLogType() {
        return logType_;
      }
      /**
       * <pre>
       * LogType
       * </pre>
       *
       * <code>int32 log_type = 1;</code>
       * @param value The logType to set.
       * @return This builder for chaining.
       */
      public Builder setLogType(int value) {
        
        logType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * LogType
       * </pre>
       *
       * <code>int32 log_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLogType() {
        
        logType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object clientIp_ = "";
      /**
       * <code>string client_ip = 2;</code>
       * @return The clientIp.
       */
      public java.lang.String getClientIp() {
        java.lang.Object ref = clientIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string client_ip = 2;</code>
       * @return The bytes for clientIp.
       */
      public com.google.protobuf.ByteString
          getClientIpBytes() {
        java.lang.Object ref = clientIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string client_ip = 2;</code>
       * @param value The clientIp to set.
       * @return This builder for chaining.
       */
      public Builder setClientIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string client_ip = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientIp() {
        
        clientIp_ = getDefaultInstance().getClientIp();
        onChanged();
        return this;
      }
      /**
       * <code>string client_ip = 2;</code>
       * @param value The bytes for clientIp to set.
       * @return This builder for chaining.
       */
      public Builder setClientIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientIp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientId_ = "";
      /**
       * <code>string client_id = 3;</code>
       * @return The clientId.
       */
      public java.lang.String getClientId() {
        java.lang.Object ref = clientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string client_id = 3;</code>
       * @return The bytes for clientId.
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        java.lang.Object ref = clientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string client_id = 3;</code>
       * @param value The clientId to set.
       * @return This builder for chaining.
       */
      public Builder setClientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string client_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientId() {
        
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      /**
       * <code>string client_id = 3;</code>
       * @param value The bytes for clientId to set.
       * @return This builder for chaining.
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientVersion_ = "";
      /**
       * <code>string client_version = 4;</code>
       * @return The clientVersion.
       */
      public java.lang.String getClientVersion() {
        java.lang.Object ref = clientVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string client_version = 4;</code>
       * @return The bytes for clientVersion.
       */
      public com.google.protobuf.ByteString
          getClientVersionBytes() {
        java.lang.Object ref = clientVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string client_version = 4;</code>
       * @param value The clientVersion to set.
       * @return This builder for chaining.
       */
      public Builder setClientVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string client_version = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientVersion() {
        
        clientVersion_ = getDefaultInstance().getClientVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string client_version = 4;</code>
       * @param value The bytes for clientVersion to set.
       * @return This builder for chaining.
       */
      public Builder setClientVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientVersion_ = value;
        onChanged();
        return this;
      }

      private boolean enableMonitor_ ;
      /**
       * <code>bool enable_monitor = 5;</code>
       * @return The enableMonitor.
       */
      @java.lang.Override
      public boolean getEnableMonitor() {
        return enableMonitor_;
      }
      /**
       * <code>bool enable_monitor = 5;</code>
       * @param value The enableMonitor to set.
       * @return This builder for chaining.
       */
      public Builder setEnableMonitor(boolean value) {
        
        enableMonitor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool enable_monitor = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnableMonitor() {
        
        enableMonitor_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object configuration_ = "";
      /**
       * <code>string configuration = 6;</code>
       * @return The configuration.
       */
      public java.lang.String getConfiguration() {
        java.lang.Object ref = configuration_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          configuration_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string configuration = 6;</code>
       * @return The bytes for configuration.
       */
      public com.google.protobuf.ByteString
          getConfigurationBytes() {
        java.lang.Object ref = configuration_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          configuration_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string configuration = 6;</code>
       * @param value The configuration to set.
       * @return This builder for chaining.
       */
      public Builder setConfiguration(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        configuration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string configuration = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearConfiguration() {
        
        configuration_ = getDefaultInstance().getConfiguration();
        onChanged();
        return this;
      }
      /**
       * <code>string configuration = 6;</code>
       * @param value The bytes for configuration to set.
       * @return This builder for chaining.
       */
      public Builder setConfigurationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        configuration_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:oms.ClientHandShake)
    }

    // @@protoc_insertion_point(class_scope:oms.ClientHandShake)
    private static final com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake();
    }

    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientHandShake>
        PARSER = new com.google.protobuf.AbstractParser<ClientHandShake>() {
      @java.lang.Override
      public ClientHandShake parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientHandShake(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientHandShake> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientHandShake> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.ClientHandShake getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RuntimeStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:oms.RuntimeStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string ip = 1;</code>
     * @return The ip.
     */
    java.lang.String getIp();
    /**
     * <code>string ip = 1;</code>
     * @return The bytes for ip.
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>int32 port = 2;</code>
     * @return The port.
     */
    int getPort();

    /**
     * <code>int32 stream_count = 3;</code>
     * @return The streamCount.
     */
    int getStreamCount();

    /**
     * <code>int32 worker_count = 4;</code>
     * @return The workerCount.
     */
    int getWorkerCount();
  }
  /**
   * Protobuf type {@code oms.RuntimeStatus}
   */
  public static final class RuntimeStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:oms.RuntimeStatus)
      RuntimeStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RuntimeStatus.newBuilder() to construct.
    private RuntimeStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RuntimeStatus() {
      ip_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RuntimeStatus();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RuntimeStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 16: {

              port_ = input.readInt32();
              break;
            }
            case 24: {

              streamCount_ = input.readInt32();
              break;
            }
            case 32: {

              workerCount_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.internal_static_oms_RuntimeStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.internal_static_oms_RuntimeStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus.class, com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus.Builder.class);
    }

    public static final int IP_FIELD_NUMBER = 1;
    private volatile java.lang.Object ip_;
    /**
     * <code>string ip = 1;</code>
     * @return The ip.
     */
    @java.lang.Override
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>string ip = 1;</code>
     * @return The bytes for ip.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 2;
    private int port_;
    /**
     * <code>int32 port = 2;</code>
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
      return port_;
    }

    public static final int STREAM_COUNT_FIELD_NUMBER = 3;
    private int streamCount_;
    /**
     * <code>int32 stream_count = 3;</code>
     * @return The streamCount.
     */
    @java.lang.Override
    public int getStreamCount() {
      return streamCount_;
    }

    public static final int WORKER_COUNT_FIELD_NUMBER = 4;
    private int workerCount_;
    /**
     * <code>int32 worker_count = 4;</code>
     * @return The workerCount.
     */
    @java.lang.Override
    public int getWorkerCount() {
      return workerCount_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ip_);
      }
      if (port_ != 0) {
        output.writeInt32(2, port_);
      }
      if (streamCount_ != 0) {
        output.writeInt32(3, streamCount_);
      }
      if (workerCount_ != 0) {
        output.writeInt32(4, workerCount_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ip_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, port_);
      }
      if (streamCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, streamCount_);
      }
      if (workerCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, workerCount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus)) {
        return super.equals(obj);
      }
      com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus other = (com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus) obj;

      if (!getIp()
          .equals(other.getIp())) return false;
      if (getPort()
          != other.getPort()) return false;
      if (getStreamCount()
          != other.getStreamCount()) return false;
      if (getWorkerCount()
          != other.getWorkerCount()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (37 * hash) + STREAM_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getStreamCount();
      hash = (37 * hash) + WORKER_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getWorkerCount();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code oms.RuntimeStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:oms.RuntimeStatus)
        com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.internal_static_oms_RuntimeStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.internal_static_oms_RuntimeStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus.class, com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus.Builder.class);
      }

      // Construct using com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ip_ = "";

        port_ = 0;

        streamCount_ = 0;

        workerCount_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.internal_static_oms_RuntimeStatus_descriptor;
      }

      @java.lang.Override
      public com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus getDefaultInstanceForType() {
        return com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus.getDefaultInstance();
      }

      @java.lang.Override
      public com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus build() {
        com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus buildPartial() {
        com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus result = new com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus(this);
        result.ip_ = ip_;
        result.port_ = port_;
        result.streamCount_ = streamCount_;
        result.workerCount_ = workerCount_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus) {
          return mergeFrom((com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus other) {
        if (other == com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus.getDefaultInstance()) return this;
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (other.getStreamCount() != 0) {
          setStreamCount(other.getStreamCount());
        }
        if (other.getWorkerCount() != 0) {
          setWorkerCount(other.getWorkerCount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>string ip = 1;</code>
       * @return The ip.
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ip = 1;</code>
       * @return The bytes for ip.
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ip = 1;</code>
       * @param value The ip to set.
       * @return This builder for chaining.
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 1;</code>
       * @param value The bytes for ip to set.
       * @return This builder for chaining.
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 2;</code>
       * @return The port.
       */
      @java.lang.Override
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 2;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }

      private int streamCount_ ;
      /**
       * <code>int32 stream_count = 3;</code>
       * @return The streamCount.
       */
      @java.lang.Override
      public int getStreamCount() {
        return streamCount_;
      }
      /**
       * <code>int32 stream_count = 3;</code>
       * @param value The streamCount to set.
       * @return This builder for chaining.
       */
      public Builder setStreamCount(int value) {
        
        streamCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 stream_count = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStreamCount() {
        
        streamCount_ = 0;
        onChanged();
        return this;
      }

      private int workerCount_ ;
      /**
       * <code>int32 worker_count = 4;</code>
       * @return The workerCount.
       */
      @java.lang.Override
      public int getWorkerCount() {
        return workerCount_;
      }
      /**
       * <code>int32 worker_count = 4;</code>
       * @param value The workerCount to set.
       * @return This builder for chaining.
       */
      public Builder setWorkerCount(int value) {
        
        workerCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 worker_count = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearWorkerCount() {
        
        workerCount_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:oms.RuntimeStatus)
    }

    // @@protoc_insertion_point(class_scope:oms.RuntimeStatus)
    private static final com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus();
    }

    public static com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RuntimeStatus>
        PARSER = new com.google.protobuf.AbstractParser<RuntimeStatus>() {
      @java.lang.Override
      public RuntimeStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RuntimeStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RuntimeStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RuntimeStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.oceanbase.clogproxy.common.packet.protocol.LogProxyProto.RuntimeStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_oms_PbPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_oms_PbPacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_oms_ClientHandShake_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_oms_ClientHandShake_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_oms_RuntimeStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_oms_RuntimeStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024proto/logproxy.proto\022\003oms\"@\n\010PbPacket\022" +
      "\014\n\004type\030\001 \001(\005\022\025\n\rcompress_type\030\002 \001(\005\022\017\n\007" +
      "payload\030d \001(\014\"\220\001\n\017ClientHandShake\022\020\n\010log" +
      "_type\030\001 \001(\005\022\021\n\tclient_ip\030\002 \001(\t\022\021\n\tclient" +
      "_id\030\003 \001(\t\022\026\n\016client_version\030\004 \001(\t\022\026\n\016ena" +
      "ble_monitor\030\005 \001(\010\022\025\n\rconfiguration\030\006 \001(\t" +
      "\"U\n\rRuntimeStatus\022\n\n\002ip\030\001 \001(\t\022\014\n\004port\030\002 " +
      "\001(\005\022\024\n\014stream_count\030\003 \001(\005\022\024\n\014worker_coun" +
      "t\030\004 \001(\005B?\n.com.oceanbase.clogproxy.commo" +
      "n.packet.protocolB\rLogProxyProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_oms_PbPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_oms_PbPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_oms_PbPacket_descriptor,
        new java.lang.String[] { "Type", "CompressType", "Payload", });
    internal_static_oms_ClientHandShake_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_oms_ClientHandShake_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_oms_ClientHandShake_descriptor,
        new java.lang.String[] { "LogType", "ClientIp", "ClientId", "ClientVersion", "EnableMonitor", "Configuration", });
    internal_static_oms_RuntimeStatus_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_oms_RuntimeStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_oms_RuntimeStatus_descriptor,
        new java.lang.String[] { "Ip", "Port", "StreamCount", "WorkerCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
