/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oceanbase_logclient_LibOblogReaderJni */

#ifndef _Included_com_oceanbase_logclient_LibOblogReaderJni
#define _Included_com_oceanbase_logclient_LibOblogReaderJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_oceanbase_logclient_LibOblogReaderJni
 * Method:    init
 * Signature: (Ljava/util/HashMap;J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_oceanbase_logclient_LibOblogReaderJni_init(JNIEnv*, jclass, jobject, jlong);

/*
 * Class:     com_oceanbase_logclient_LibOblogReaderJni
 * Method:    start
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_oceanbase_logclient_LibOblogReaderJni_start(JNIEnv*, jclass);

/*
 * Class:     com_oceanbase_logclient_LibOblogReaderJni
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_oceanbase_logclient_LibOblogReaderJni_stop(JNIEnv*, jclass);

/*
 * Class:     com_oceanbase_logclient_LibOblogReaderJni
 * Method:    next
 * Signature: ()Lcom/oceanbase/oms/store/client/message/drcmessage/DrcNETBinaryRecord;
 */
JNIEXPORT jobject JNICALL Java_com_oceanbase_logclient_LibOblogReaderJni_next__(JNIEnv*, jclass);

/*
 * Class:     com_oceanbase_logclient_LibOblogReaderJni
 * Method:    next
 * Signature: (J)Lcom/oceanbase/oms/store/client/message/drcmessage/DrcNETBinaryRecord;
 */
JNIEXPORT jobject JNICALL Java_com_oceanbase_logclient_LibOblogReaderJni_next__J(JNIEnv*, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
